### ISSUE TITLE
[Bug]: first launch failed

### ISSUE THREAD

**Issue by lingsamuel** [Monitor144hz/Pandora-Behaviour-Engine-Plus#136]
### Version

v1.1.8-alphae

### Provide Instructions on Reproducing the Problem

I simply install Pandora in MO2, start it, check my mods, and launch it for the first time, it failed.

But I can't reproduce it either. It can successfully generate output now (without any change).

### Provide Relevant Files

Here is the checked mods
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/14567045/a485c70c-66f5-4d1a-838b-2d0b7ece0072)
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/14567045/3f67a350-220c-4b05-bca6-ac644af1751e)

Here is `Engine.log` from the failed run. ~~I don't have the full output of failed run anymore because the next run succeeds.~~ Failed output is empty.
```log
INFO : Skyrim Patcher 1.1.6-alpha
WARN : Dispatcher > "Some Creature Behavior Bug Fixes" > draugrskeletonproject~draugrbehavior > Remove > Element > #0097/transitions/Element3 > FAILED
WARN : Dispatcher > "Some Creature Behavior Bug Fixes" > draugrskeletonproject~draugrbehavior > Remove > Element > #0097/transitions/Element4 > FAILED
WARN : Dispatcher > "True Directional Movement - 360 Horse Archery" > defaultfemale~horsebehavior > Replace > Text > #0742/errorOutTranslation > FAILED
WARN : Dispatcher > "HotKeySkill" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "SCAR" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "Distar Unblockable" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Validator > defaultfemale~magicbehavior > Duplicate Event > PIE > Index > 109 > REMOVED
WARN : Validator > defaultmale~0_master > Duplicate Event > PIE > Index > 23 > REMOVED
WARN : Validator > defaultmale~0_master > Duplicate Event > PIE > Index > 0 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_Start > Index > 138 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > PIE > Index > 117 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_EndAnimation > Index > 116 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_WinOpen > Index > 115 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_WinClose > Index > 114 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_PowerWinOpen > Index > 113 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_PowerWinClose > Index > 112 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_InputBuffer > Index > 111 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > PIE > Index > 108 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Variable > MCO_BlendLength > Index > 5 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Variable > MCO_IsInRecovery > Index > 4 > REMOVED
FATAL : Export > defaultfemale~1hm_behavior > FAILED > System.InvalidCastException: Unable to cast object of type 'HKX2.hkbBlendingTransitionEffect' to type 'HKX2.hkbStateMachineEventPropertyArray'.
   at HKX2.XmlDeserializer.ReadClassPointer[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 163
   at HKX2.hkbStateMachineStateInfo.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Autogen\hkbStateMachineStateInfo.cs:line 67
   at HKX2.XmlDeserializer.ReadClassPointerArray[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 202
   at HKX2.hkbStateMachine.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Autogen\hkbStateMachine.cs:line 156
   at HKX2.XmlDeserializer.ReadClassPointerArray[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 202
   at HKX2.hkbManualSelectorGenerator.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Autogen\hkbManualSelectorGenerator.cs:line 42
   at HKX2.XmlDeserializer.ReadClassPointer[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 169
   at HKX2.hkbModifierGenerator.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Autogen\hkbModifierGenerator.cs:line 35
   at HKX2.XmlDeserializer.ReadClassPointer[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 169
   at HKX2.hkbStateMachineStateInfo.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Autogen\hkbStateMachineStateInfo.cs:line 70
   at HKX2.XmlDeserializer.ReadClassPointerArray[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 202
   at HKX2.hkbStateMachine.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Autogen\hkbStateMachine.cs:line 156
   at HKX2.XmlDeserializer.ReadClassPointer[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 169
   at HKX2.hkbModifierGenerator.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Autogen\hkbModifierGenerator.cs:line 35
   at HKX2.XmlDeserializer.ReadClassPointer[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 169
   at HKX2.hkbStateMachineStateInfo.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Autogen\hkbStateMachineStateInfo.cs:line 70
   at HKX2.XmlDeserializer.ReadClassPointerArray[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 202
   at HKX2.hkbStateMachine.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Autogen\hkbStateMachine.cs:line 156
   at HKX2.XmlDeserializer.ReadClassPointer[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 169
   at HKX2.hkbBehaviorGraph.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Autogen\hkbBehaviorGraph.cs:line 152
   at HKX2.XmlDeserializer.ReadClassPointer[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 169
   at HKX2.hkRootLevelContainerNamedVariant.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Manual\hkRootLevelContainerNamedVariant.cs:line 39
   at HKX2.XmlDeserializer.ReadClassArray[T](XElement element, String name) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 126
   at HKX2.hkRootLevelContainer.ReadXml(XmlDeserializer xd, XElement xe) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\Manual\hkRootLevelContainer.cs:line 31
   at HKX2.XmlDeserializer.Deserialize(Stream stream, HKXHeader header, Boolean ignoreNonFatalError) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\third_party\HKX2-Library\HKX2 WPF\XMLDeserializer.cs:line 55
   at Pandora.Patch.Patchers.Skyrim.Hkx.PackFile.Export() in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\PandoraPlus\MVVM\Model\Patch\Patchers\Skyrim\Hkx\PackFile.cs:line 199
```

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by elbadcode** [comment]
Maybe there's a deeper issue monitor has already narrowed it down to, but to me this seems like it may be due to an old output existing since your log says 1.1.6 and you stated you were using 1.1.8. I always make it a habit of creating a new output folder and disabling the old one in mo2 when there's an update which may prevent this issue.

**Comment by Monitor144hz** [comment]
@lingsamuel does this issue exist in the latest version?

**Comment by lingsamuel** [comment]
Sorry, I can't verify it. Like what I said, it only happens in the first launch. I can't reproduce this issue even in old version.
